finanzaspersonales/finanzas/urls.py
from django.urls import path
from django.views.generic import TemplateView
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('tegresos/',views.egresos,name='Tipos de egresos'),
    path('tpagos/',views.tpago,name='Tipos de egresos'),
    path('trenglones/',views.trenglones,name='Tipos de egresos'),
    path('tingresos/',views.ingresos,name='Tipos de egresos'),
    path('edit/<str:tipo>/<int:id>',views.editcontenido,name='Tipos de egresos'),
    path('elimegreso/',views.elimegreso,name='Tipos de egresos'),
    path('creausario',views.creausario,name='Crear usuarios'),
    path('usuarios/',views.Usuarios,name='Usuarios'),
]

finanzaspersonales/finanzaspersonales/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('finanzas.urls')),
    path('admin/', admin.site.urls),
]

finanzaspersonales/finanzas/models.py
from django.db import models
from django.core.validators import MinValueValidator, MaxValueValidator
from django.utils import timezone

# Create your models here.
class TipoEgresos(models.Model):
    id = models.AutoField(primary_key=True, help_text="ID tipo de egreso")
    descripcion = models.CharField(max_length=50, help_text="Descripcion del tipo de Egreso")
    estado = models.CharField(max_length=1, choices=(('A', 'Activo'),('I', 'Inactivo')), blank=True, default='A', help_text='Estado del egreso')
    # Métodos
    def __str__(self):
        return "{}".format('Tipos de Egresos')


class TipoIngresos(models.Model):
    id = models.AutoField(primary_key=True, help_text="ID tipo de ingreso")
    descripcion = models.CharField(max_length=50, help_text="Descripcion del tipo de Ingreso")
    estado = models.CharField(max_length=1, choices=(('A', 'Activo'),('I', 'Inactivo')), blank=True, default='A', help_text='Estado del Ingreso')
    # Métodos
    def __str__(self):
        return "{}".format('Tipos de Ingresos')


class RenglonEgresos(models.Model):
    id = models.AutoField(primary_key=True, help_text="ID renglon de egreso")
    descripcion = models.CharField(max_length=50, help_text="Renglones de Egresos")
    estado = models.CharField(max_length=1, choices=(('A', 'Activo'),('I', 'Inactivo')), blank=True, default='A', help_text='Estado del renglon')
    # Métodos
    def __str__(self):
        return "{}".format('Tipos de Renglones de Egresos')


class TipoPago(models.Model):
    id = models.AutoField(primary_key=True, help_text="ID tipo de pago")
    descripcion = models.CharField(max_length=50, help_text="Tipo de Pago")
    estado = models.CharField(max_length=1, choices=(('A', 'Activo'),('I', 'Inactivo')), blank=True, default='A', help_text='Estado del tipo de pago')
    # Métodos
    def __str__(self):
        return "{}".format('Tipos de Pago')



class GestionEgresos(models.Model):
    id = models.AutoField(primary_key=True, help_text="ID Gestion de Egresos")
    tipo = models.ForeignKey('TipoEgresos', on_delete=models.SET_NULL, null=True, verbose_name ='Tipo de Egreso')
    renglon = models.ForeignKey('RenglonEgresos', on_delete=models.SET_NULL, null=True, verbose_name ='Renglon')
    tipopago = models.ForeignKey('TipoPago', on_delete=models.SET_NULL, null=True, default='X', verbose_name ='Tipo de pago')
    descripcion = models.CharField(max_length=50, help_text="Descripcion", verbose_name ='Descripcion')
    estado = models.CharField(max_length=1, choices=(('A', 'Activo'),('I', 'Inactivo')), blank=True, default='A', help_text='Estado del tipo de pago', verbose_name ='Estado')
    
    # Métodos
    def __str__(self):
        return self.descripcion



class FuenteIngreso(models.Model):
    id = models.AutoField(primary_key=True, help_text="ID Fuente de Ingreso")
    descripcion = models.CharField(max_length=50, help_text="Descripcion")
    estado = models.CharField(max_length=1, choices=(('A', 'Activo'),('I', 'Inactivo')), blank=True, default='A', help_text='Estado Fuente de Ingreso')
    # Métodos
    def __str__(self):
        return self.descripcion



class GestionIngresos(models.Model):
    id = models.AutoField(primary_key=True, help_text="ID Gestion de Egresos")
    tipo = models.ForeignKey('TipoIngresos', on_delete=models.SET_NULL, null=True, verbose_name ='Tipo de Egreso')
    descripcion = models.CharField(max_length=50, help_text="Descripcion", verbose_name ='Descripcion')
    fuente = models.ForeignKey('FuenteIngreso', on_delete=models.SET_NULL, null=True, verbose_name ='Fuente de Ingreso')
    estado = models.CharField(max_length=1, choices=(('A', 'Activo'),('I', 'Inactivo')), blank=True, default='A', help_text='Estado del tipo de pago', verbose_name ='Estado')
    
    # Métodos
    def __str__(self):
        return self.descripcion


class usuarios(models.Model):
    id = models.AutoField(primary_key=True, help_text="ID Usuario")
    primernombre = models.CharField(max_length=15, help_text="Primer Nombre", verbose_name ="Primer Nombre")
    segundonombre  = models.CharField(max_length=15, help_text="Segundo Nombre", verbose_name ="Segundo Nombre")
    primerapellido = models.CharField(max_length=15, help_text="Primer Apellido", verbose_name ="Primer Apellido")
    segundoapellido = models.CharField(max_length=15, help_text="Segundo Apellido", verbose_name ="Segundo Apellido")
    cedula = models.CharField(max_length=11, help_text="Cedula", verbose_name = "Cedula")
    limiteegresos = models.IntegerField(validators=[MinValueValidator(0)],default=0, help_text='Limite de Egresos', verbose_name ='Limite de Egresos')
    tipopersona = models.CharField(max_length=1, choices=(('F', 'Fisica'),('J', 'Juridico')), blank=True, default='A', help_text='Tipo de persona, Fisica o Juridica', verbose_name ='Tipo Persona')
    fechacorte = models.DateField(help_text='Fecha de Corte', verbose_name ='Fecha de Corte')
    estado = models.CharField(max_length=1, choices=(('A', 'Activo'),('I', 'Inactivo')), blank=True, default='A', help_text='Estado del tipo de pago', verbose_name ='Estado')
    
    # Métodos
    def __str__(self):
        return "{} {} {} {}".format(self.primernombre, 
                                    self.segundonombre, 
                                    self.primerapellido, 
                                    self.segundoapellido)



class Transacciones(models.Model):
    id = models.AutoField(primary_key=True, help_text="ID Transaccion")
    tipotransaccion = models.CharField(max_length=1, choices=(('I', 'Ingreso'),('E', 'Egreso')), blank=True, default='A', help_text='Tipo de Ingreso', verbose_name ='Tipo de Ingreso')
    usuario = models.ForeignKey('usuarios', on_delete=models.SET_NULL, null=True, verbose_name ='Usuario')
    tipo = models.CharField(max_length=1, choices=(('I', 'Ingreso'),('G', 'Gasto')), blank=True, default='A', help_text='Tipo de Transaccion', verbose_name ='Tipo de Transaccion')
    tipopago = models.ForeignKey('TipoIngresos', on_delete=models.SET_NULL, null=True, verbose_name ='Tipo de Pago')
    fechatransaccion = models.DateField(help_text='Fecha de la transaccion', verbose_name ='Fecha de la transaccion')
    fecharegistro = models.DateField(default=timezone.now,help_text='Fecha de registro', verbose_name ='Fecha de registro')
    monto = models.IntegerField(validators=[MinValueValidator(0)],default=0, help_text='Monto Transaccion', verbose_name ='Monto Transaccion')
    notarjeta = models.CharField(max_length=100, help_text="Numero de tarjeta CR", verbose_name ="Numero de tarjeta CR")
    comentario = models.CharField(max_length=100, help_text="Comentario", verbose_name ="Comentario")
    estado = models.CharField(max_length=1, choices=(('A', 'Activo'),('I', 'Inactivo')), blank=True, default='A', help_text='Estado', verbose_name ='Estado')
    
    # Métodos
    def __str__(self):
        return "{} {}".format(self.tipopago,self.usuario,)



class Corte(models.Model):
    id = models.AutoField(primary_key=True, help_text="ID Transaccion")
    ano = models.IntegerField(validators=[MinValueValidator(0)],help_text='Año', verbose_name ='Año')
    mes = models.IntegerField(validators=[MinValueValidator(1)],help_text='Mes', verbose_name ='Mes')
    fechacorte = models.DateField(default=timezone.now,help_text='Fecha del Corte', verbose_name ='Fecha del Corte')
    balanceinicial = models.IntegerField(validators=[MinValueValidator(0)],default=0,help_text='Balance Inicial', verbose_name ='Balance Inicial')
    totalingresos = models.IntegerField(validators=[MinValueValidator(0)],default=0,help_text='Total Ingresos', verbose_name ='Total Ingresos')
    totalegresos = models.IntegerField(validators=[MinValueValidator(0)],default=0,help_text='Total Egresos', verbose_name ='Total Egresos')
    balancecorte = models.IntegerField(validators=[MinValueValidator(0)],default=0,help_text='Balance Al Corte', verbose_name ='Balance Al Corte')
    # Métodos
    def __str__(self):
        return self.descripcion

finanzaspersonales/finanzas/forms.py
from django import forms
from django.forms import ModelForm, Textarea
from .models import usuarios


class UsuarioForm(forms.Form):
    primernombre= forms.CharField(max_length=15,label='Primer Nombre',widget= forms.TextInput(attrs={'class':'form-control','id':'exampleInputName1','placeholder':'Primer Nombre'}))
    segundonombre = forms.CharField(max_length=15,label='Segundo Nombre',widget= forms.TextInput(attrs={'class':'form-control','id':'exampleInputName1','placeholder':'Segundo Nombre'}))
    primerapellido = forms.CharField(max_length=15,label='Primer Apellido',widget= forms.TextInput(attrs={'class':'form-control','id':'exampleInputName1','placeholder':'Primer Apellido'}))
    segundoapellido = forms.CharField(max_length=15,label='Segundo Apellido',widget= forms.TextInput(attrs={'class':'form-control','id':'exampleInputName1','placeholder':'Segundo Apellido'}))
    cedula = forms.CharField(max_length=13,label='Cedula',widget= forms.TextInput(attrs={'class':'form-control','id':'exampleInputName1','placeholder':'Cedula'}))
    limiteegresos = forms.IntegerField(label='Limite de Egresos',widget= forms.TextInput(attrs={'class':'form-control','id':'exampleInputName1','placeholder':'Limite de Egresos'}))
    tipopersona = forms.ChoiceField(label='Tipo Persona',widget= forms.TextInput(attrs={'class':'form-control','id':'exampleInputName1','placeholder':'Tipo Persona'}))
    estado = forms.ChoiceField(label='Estado')


class EgresoForm(forms.Form):
    descripcion = forms.CharField(max_length=15,label='Primer Nombre',widget= forms.TextInput(attrs={'class':'form-control','id':'exampleInputName1','placeholder':'Primer Nombre'}))
    estado = forms.MultipleChoiceField()

finanzaspersonales/finanzas/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.template import loader
from django.views.generic import ListView, DetailView, TemplateView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy
from django.db import models
from . import models
from .forms import *



# Create your views here.
def index(request):
    template = 'finanzas/index.html'
    context = {'':''}
    return render(request, template, context)


def transacciones(request):
    template = 'finanzas/transacciones.html'
    context = {'':''}
    return render(request, template, context)

## Usuarios ##
def Usuarios(request):
    contenido = models.usuarios.objects.all()
    template = 'finanzas/usuarios.html'
    context = {'listausuarios': contenido,'':''}
    return render(request, template, context)


def egresos(request):
    contenido = models.TipoEgresos.objects.all()
    template = 'finanzas/tlistado.html'
    context = {'contenido': contenido,'titulo':models.TipoEgresos,'tipot':'e'}
    return render(request, template, context)

def ingresos(request):
    contenido = models.TipoIngresos.objects.all()
    template = 'finanzas/tlistado.html'
    context = {'contenido': contenido,'titulo':models.TipoIngresos,'tipot':'i'}
    return render(request, template, context)

def tpago(request):
    contenido = models.TipoPago.objects.all()
    template = 'finanzas/tlistado.html'
    context = {'contenido': contenido,'titulo':models.TipoPago,'tipot':'p'}
    return render(request, template, context)

def trenglones(request):
    contenido = models.RenglonEgresos.objects.all()
    template = 'finanzas/tlistado.html'
    context = {'contenido': contenido,'titulo':models.RenglonEgresos,'tipot':'r'}
    return render(request, template, context)

def creausario(request):
    form = UsuarioForm(request.POST)
    if request.method == "POST":
        form = UsuarioForm(request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            post.primernombre = form.cleaned_data['primernombre']
            post.segundonombre = form.cleaned_data['segundonombre']
            post.primerapellido = form.cleaned_data['primerapellido']
            post.segundoapellido = form.cleaned_data['segundoapellido']
            post.cedula = form.cleaned_data['cedula']
            post.limiteegresos = form.cleaned_data['limiteegresos']
            post.tipopersona = form.cleaned_data['tipopersona']
            post.fechacorte = form.cleaned_data['fechacorte']
            post.estado = form.cleaned_data['estado']
            post.save()
            return redirect('detalleusuario', pk=post.pk)
        else:
            form = UsuarioForm()

    template = 'finanzas/creausario.html'
    context = {'form': form}
    return render(request, template, context)
 

def editcontenido(request,tipo,id):
    form = EgresoForm(request.POST)
    if request.method == "POST":
        if tipo == 'e':
            form = EgresoForm(request.POST)
            goto = '/tegresos/'
        elif tipo == 'i':
            form = UsuarioForm(request.POST)
            goto = '/tingresos/'
        elif tipo == 'r':
            form = UsuarioForm(request.POST)
            goto = '/trenglones/'        
        elif tipo == 'p':
            form = UsuarioForm(request.POST)
            goto = '/tpagos/'

        if form.is_valid():
            forma = form.save(commit=False)
            forma.descripcion = form.cleaned_data['primernombre']
            forma.estado = form.cleaned_data['segundonombre']
            forma.save()
            return redirect(goto, pk=post.pk)
        else:
            form = UsuarioForm()

    template = 'finanzas/editarcontenido.html'
    context = {'form': form}
    return render(request, template, context)


def elimegreso(request):
    pass

finanzaspersonales/finanzas/templates/finanzas/base.html
{% load static %}
{% load i18n %}
<!DOCTYPE html>
<html lang="en">
<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <title>Homepage</title>
  <!-- plugins:css -->
  <link rel="stylesheet" href="{% static "finanzas/vendors/iconfonts/mdi/css/materialdesignicons.min.css" %}">
  <link rel="stylesheet" href="{% static "finanzas/vendors/css/vendor.bundle.base.css" %}">
  <link rel="stylesheet" href="{% static "finanzas/vendors/css/vendor.bundle.addons.css" %}">
  <!-- endinject -->
  <!-- plugin css for this page -->
  <!-- End plugin css for this page -->
  <!-- inject:css -->
  <link rel="stylesheet" href="{% static "finanzas/css/style.css" %}">
  <!-- endinject -->
  <link rel="shortcut icon" href="{% static "finanzas/images/favicon.png" %}" />
</head>

<body>
  <div class="container-scroller">
          {% block navbar %}
{% include "finanzas/partials/navbar.html" %}
        {% endblock %}

    <div class="container-fluid page-body-wrapper">
      <!-- partial:partials/_sidebar.html -->
          {% block sidebar %}
{% include "finanzas/partials/sidebar.html" %}
        {% endblock %}
      <!-- partial -->
      <div class="main-panel">
        <div class="content-wrapper">

          {% block content %}

        {% endblock %}



        </div>
        <!-- content-wrapper ends -->
        <!-- partial:partials/_footer.html -->

          {% block footer %}
{% include "finanzas/partials/footer.html" %}
        {% endblock %}
        <!-- partial -->
      </div>
      <!-- main-panel ends -->
    </div>
    <!-- page-body-wrapper ends -->
  </div>
  <!-- container-scroller -->

  <!-- plugins:js -->
  <script src="{% static "finanzas/vendors/js/vendor.bundle.base.js" %}"></script>
  <script src="{% static "finanzas/vendors/js/vendor.bundle.addons.js" %}"></script>
  <!-- endinject -->
  <!-- Plugin js for this page-->
  <!-- End plugin js for this page-->
  <!-- inject:js -->
  <script src="{% static "finanzas/js/off-canvas.js" %}"></script>
  <script src="{% static "finanzas/js/misc.js" %}"></script>
  <!-- endinject -->
  <!-- Custom js for this page-->
  <script src="{% static "finanzas/js/dashboard.js" %}"></script>
  <!-- End custom js for this page-->
</body>

</html>

finanzaspersonales/finanzas/templates/finanzas/corte.html
{% extends 'finanzas/base.html' %}
{% block content %}

{% endblock %}

finanzaspersonales/finanzas/templates/finanzas/creausario.html
{% extends 'finanzas/base.html' %}
{% block content %}
<div class="col-md-6 grid-margin stretch-card">
              <div class="card">
                <div class="card-body">
                  <h4 class="card-title">Creacion de Usuario</h4>
                  <form class="forms-sample" method="POST"> {% csrf_token %}

               <div class="form-group">
                      <label for="exampleInputName1">{{form.primernombre.label}}</label>
                                      {{ form.primernombre }}
               </div>
               <div class="form-group">
                      <label for="exampleInputName1">{{form.segundonombre.label}}</label>
                                      {{ form.segundonombre }}
               </div>
               <div class="form-group">
                      <label for="exampleInputName1">{{form.primerapellido.label}}</label>
                                      {{ form.primerapellido }}
               </div>
               <div class="form-group">
                      <label for="exampleInputName1">{{form.segundoapellido.label}}</label>
                                      {{ form.segundoapellido }}
               </div>
               <div class="form-group">
                      <label for="exampleInputName1">{{form.cedula.label}}</label>
                                      {{ form.cedula }}
               </div>
               <div class="form-group">
                      <label for="exampleInputName1">{{form.limiteegreso.label}}</label>
                                      {{ form.limiteegreso }}
               </div>
               <div class="form-group">
                      <label for="exampleInputName1">{{form.tipopersona.label}}</label>
                                      {% for opcion in form.tipopersona %}
                                          {{opcion.label}}
                                      {% endfor %}
               </div>

                     {{ form.estado }}


                  </form>
                </div>
              </div>
            </div>
{% endblock %}

finanzaspersonales/finanzas/templates/finanzas/editarcontenido.html
{% extends 'finanzas/base.html' %}
{% block content %}
<div class="col-md-6 grid-margin stretch-card">
              <div class="card">
                <div class="card-body">
                  <h4 class="card-title">Editar</h4>
                  <form class="forms-sample" method="POST"> {% csrf_token %}

               <div class="form-group">
                      <label for="exampleInputName1">{{form.descripcion.label}}</label>
                                      {{ form.descripcion }}
               </div>
               <div class="form-group">
                      <label for="exampleInputName1">{{form.estado.label}}</label>
                                      {{ form.estado }}
               </div>
                  </form>
                </div>
              </div>
            </div>
{% endblock %}

finanzaspersonales/finanzas/templates/finanzas/gegresos.html
{% extends 'finanzas/base.html' %}
{% block content %}

{% endblock %}

finanzaspersonales/finanzas/templates/finanzas/gingresos.html
{% extends 'finanzas/base.html' %}
{% block content %}

{% endblock %}

finanzaspersonales/finanzas/templates/finanzas/index.html
{% extends 'finanzas/base.html' %}
{% block content %}

{% endblock %}

finanzaspersonales/finanzas/templates/finanzas/regresos.html
{% extends 'finanzas/base.html' %}
{% block content %}

{% endblock %}

finanzaspersonales/finanzas/templates/finanzas/tingresos.html
{% extends 'finanzas/base.html' %}
{% block content %}

{% endblock %}

finanzaspersonales/finanzas/templates/finanzas/tlistado.html
{% extends 'finanzas/base.html' %}
{% block content %}
   <div class="card">
      <div class="card-body">
         <h4 class="card-title">{{ titulo }}</h4>
         <div class="col-sm-6">
                  <a href="/creaegreso" class="btn btn-success"><i class="material-icons"></i> <span>Nuevo</span></a>                 
               </div>
         <p class="card-description">
         </p>

         <div class="table-responsive">
            <table class="table table-bordered">
               <thead>
                  <tr>
                     <th>
                        #
                     </th>
                     <th>
                        Nombre
                     </th>
                     <th>
                        Estado
                     </th>
                     <th>
                        Accion
                     </th>
                  </tr>
               </thead>
               <tbody>
                  {% for opcion in contenido %}
                  <tr>
                     <td>
                        {{ opcion.id }}
                     </td>
                                          <td>
                        {{ opcion.descripcion }}
                     </td>
                     <td>
                       {{ opcion.get_estado_display }}
                     </td>
                     <td>

<a class="btn btn-primary btn-sm" href="/edit/{{tipot}}/{{opcion.id }}" role="button">Edit</a>
<a class="btn btn-danger btn-sm" href="/elim/{{tipot}}/{{opcion.id }}" role="button">Elim</a>
                     </td>
                        
                  </tr>
                  {% endfor %}
               </tbody>
            </table>
         </div>
      </div>
   </div>
{% endblock %}

finanzaspersonales/finanzas/templates/finanzas/tpago.html
{% load static %}
{% load i18n %}
<!DOCTYPE html>
<html lang="en">
<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <title>Homepage</title>
  <!-- plugins:css -->
  <link rel="stylesheet" href="{% static "finanzas/vendors/iconfonts/mdi/css/materialdesignicons.min.css" %}">
  <link rel="stylesheet" href="{% static "finanzas/vendors/css/vendor.bundle.base.css" %}">
  <link rel="stylesheet" href="{% static "finanzas/vendors/css/vendor.bundle.addons.css" %}">
  <!-- endinject -->
  <!-- plugin css for this page -->
  <!-- End plugin css for this page -->
  <!-- inject:css -->
  <link rel="stylesheet" href="{% static "finanzas/css/style.css" %}">
  <!-- endinject -->
  <link rel="shortcut icon" href="{% static "finanzas/images/favicon.png" %}" />
</head>

<body>
  <div class="container-scroller">
          {% block navbar %}
{% include "finanzas/partials/navbar.html" %}
        {% endblock %}

    <div class="container-fluid page-body-wrapper">
      <!-- partial:partials/_sidebar.html -->
          {% block sidebar %}
{% include "finanzas/partials/sidebar.html" %}
        {% endblock %}
      <!-- partial -->
      <div class="main-panel">
        <div class="content-wrapper">

          {% block content %}

        {% endblock %}



        </div>
        <!-- content-wrapper ends -->
        <!-- partial:partials/_footer.html -->

          {% block footer %}
{% include "finanzas/partials/footer.html" %}
        {% endblock %}
        <!-- partial -->
      </div>
      <!-- main-panel ends -->
    </div>
    <!-- page-body-wrapper ends -->
  </div>
  <!-- container-scroller -->

  <!-- plugins:js -->
  <script src="{% static "finanzas/vendors/js/vendor.bundle.base.js" %}"></script>
  <script src="{% static "finanzas/vendors/js/vendor.bundle.addons.js" %}"></script>
  <!-- endinject -->
  <!-- Plugin js for this page-->
  <!-- End plugin js for this page-->
  <!-- inject:js -->
  <script src="{% static "finanzas/js/off-canvas.js" %}"></script>
  <script src="{% static "finanzas/js/misc.js" %}"></script>
  <!-- endinject -->
  <!-- Custom js for this page-->
  <script src="{% static "finanzas/js/dashboard.js" %}"></script>
  <!-- End custom js for this page-->
</body>

</html>

finanzaspersonales/finanzas/templates/finanzas/transacciones.html
{% extends 'finanzas/base.html' %}
{% block content %}

{% endblock %}

finanzaspersonales/finanzas/templates/finanzas/usuarios.html
{% extends 'finanzas/base.html' %}
{% load humanize %}
{% block content %}
   <div class="card">
      <div class="card-body">
         <h4 class="card-title">Usuarios</h4>
         <div class="col-sm-6">
                  <a href="/creausuario" class="btn btn-success"><i class="material-icons"></i> <span>Nuevo</span></a>                 
               </div>
         <p class="card-description">
         </p>

         <div class="table-responsive">
            <table class="table table-bordered">
               <thead>
                  <tr>
                     <th>
                        #
                     </th>
                     <th>
                        Nombre
                     </th>
                     <th>
                        Cedula
                     </th>
                     <th>
                        Limite de Egreso
                     </th>
                     <th>
                        Tipo
                     </th>
                     <th>
                        Fecha de corte
                     </th>
                     </th>
                     <th>
                        Estado
                     </th>
                     <th>
                        Accion
                     </th>
                  </tr>
               </thead>
               <tbody>
                  {% for user in listausuarios %}
                  <tr>
                     <td>
                        {{ user.id }}
                     </td>
                     <td>
                        {{ user }}
                     </td>
                     <td>
                        {{ user.cedula }}
                     </td>
                     <td>
                        {{ user.limiteegresos |intcomma}}
                     </td>
                     <td>
                       {{ user.get_tipopersona_display }}
                     </td>
                     <td>
                        {{ user.fechacorte }}
                     </td>
                     <td>
                        {{ user.get_estado_display }}
                     </td>
                     <td>
                            <button type="button" class="btn btn-red">5</button>
                            <button type="button" class="btn btn-green">6</button>
                     </td>
                        
                  </tr>
                  {% endfor %}
               </tbody>
            </table>
         </div>
      </div>
   </div>
{% endblock %}